name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - with: 
          node-version: 16
      - run: npm ci
      - run: npm install
      - run: npm ci --prefix ./backend
      - run: npm install --prefix ./backend
      - run: npm ci --prefix ./frontend
      - run: npm install --prefix ./frontend
      - run: npm run build --prefix ./frontend
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

