name: Release

on: 
  workflow_dispatch:

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install    
      - run: npm ci --prefix ./backend
      - run: npm install --prefix ./backend
      - run: npm ci --prefix ./frontend
      - run: npm install --prefix ./frontend
      - run: npx semantic-release          
      - run: rm -rf ./node_modules
      - run: rm -rf ./backend/node_modules
      - run: rm -rf ./frontend/node_modules
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
